export default {
	SHOW_SUCCESS_MODAL: 'SHOW_SUCCESS_MODAL',
	SHOW_ERROR_MODAL: 'SHOW_ERROR_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	APPLY_FILTERS_MODAL: 'APPLY_FILTERS_MODAL',
	ORDER_INFORMATION_MODAL: 'ORDER_INFORMATION_MODAL',
	CANCEL_ORDER_MODAL: 'CANCEL_ORDER_MODAL'
};
