export default {
	REGISTER_ORIGIN_DIRECTION: 'REGISTER_ORIGIN_DIRECTION',
	OPEN_CLOSE_ORIGIN_MODAL: 'OPEN_CLOSE_ORIGIN_MODAL',

	REGISTER_DESTINY_DIRECTION: 'REGISTER_DESTINY_DIRECTION',
	OPEN_CLOSE_DESTINY_MODAL: 'OPEN_CLOSE_DESTINY_MODAL',

	OPEN_CLOSE_CONFIRM_MODAL: 'OPEN_CLOSE_CONFIRM_MODAL',

	CHARGING_CONFIRM: 'CHARGING_CONFIRM'
};
