export default {
	OPEN_CLOSE_REGISTER_MODAL: 'OPEN_CLOSE_REGISTER_MODAL',

	OPEN_CLOSE_LOGIN_MODAL: 'OPEN_CLOSE_LOGIN_MODAL',

	START_LOGIN: 'START_LOGIN',
	SUCCESS_LOGIN: 'SUCCESS_LOGIN',
	ERROR_LOGIN: 'ERROR_LOGIN',

	LOG_OUT: 'LOG_OUT'
};
